### ISSUE TITLE
Greater than 1/Negative Probability Distributions in generated Synthea Modules

### ISSUE THREAD

**Issue by teliov** [teliov/symcat-to-synthea#15]
For the advanced symptom symcat-synthea generator, some modules end up having conditional distributions with values greater than 1 and then negative values to get the distribution sum to one.

As an example see this complex transition case from the Pharyngitis module:
```json
{
    "condition": {
        "condition_type": "And",
        "conditions": [
            {
                "condition_type": "Gender",
                "gender": "M"
            },
            {
                "condition_type": "Age",
                "operator": "<",
                "unit": "years",
                "quantity": 1
            },
            {
                "condition_type": "Race",
                "race": "Black"
            }
        ]
    },
    "distributions": [
        {
            "transition": "Pharyngitis_Infection",
            "distribution": 1.0875
        },
        {
            "transition": "No_Infection",
            "distribution": -0.08749999999999991
        }
    ]
},
```

I'm looking into this, I suspect there's something not right with the combination of the probabilities/odds for the race, gender and age.

**Comment by afansi** [comment]
will look into it too. @teliov

**Comment by teliov** [comment]
Hi @afansi , I did some more digging into this and the I am pretty sure the problem is the "normalization" of the probabilities. 

I have attached an explanation of my reasoning [symcat-negative-prob.md.pdf](https://github.com/teliov/symcat-to-synthea/files/4586782/symcat-negative-prob.md.pdf)

And my attempted fix is on the  [fixNegativeProb](https://github.com/teliov/symcat-to-synthea/tree/fixNegativeProb) branch.

Do let me know what you think!

Regards,
Stanley

**Comment by afansi** [comment]
Hi @teliov,

I was impressed by your capacity to understand the code. Your explanation
was well aligned with what was code.
I appreciated the effort for fixing the bug and also the proposed solution.

From my point of view, the problem mainly comes from the fact that the
database does not contain all the information among which the prior
regarding the consition `P(C=c)`.
As such, we need to give as input the prior to be used `prior_condition`
for each condition. We use a default of `0.5` but as observed, it is not
guarantee to keep all the `P(C|ARG)` to be less than one.
To address this issue, one could do the following:
  -  simple case: just make sure to take the `min(1, p_cond_g_sex_race_age)`
as the final result of `P(C|ARG)`.
  -  advanced case: find the `max_prior_value` of the priors that would lead
to `P(C|ARG)` be less or equal than 1. if the provided prior is less that
that `max_prior_value`, that is fine, otherwise, default the prior to that
max value.

I favoured the first option because, in most case, it leads to higher probability values `P(C|ARG)` and hence more chance for generation by Synthea.

The code proposed in the branch `neg_values` provides the code for these
two options with the second one being commented.

I found the solution with the renormalization of attributes probabilities
based on the provided priors a little bit tricky as it modifiies the proba
values provided by the symcat database. also as observed, it does not
completely solve the problem.

By the way, it appears that some symptoms probabilities `P(S|C, A, R, G)`
were also negative. Apart of a little modification I performed in order to
correct some bugs related on how these values were computed on a
probabilistc point of view, I mainly solve this issue using the simple case
option. I don't think there is much to do as all the computations are made
on the independence assumptions among the attributes since we do not have
these information present in the database. What it tell us is that those
assumptions are not necessarily true, at least for certain conditions, but
do we have choice?

Finally, as for the approach consisting in factoring probabilities for each
attribute having the condition and not having the condition and then
normalising based on the given priors for the attributes i.e gender, age,
race., I do not know if it will lead to better solution. you can give a try
and let me know.

**Comment by teliov** [comment]
Hi @afansi , thanks for your detailed reply!

I did indeed try factoring in the probabilities for each attribute given the condition being present and absent and obtaining a normalisation factor based off of that, but it gave very low probabilities. 

I suppose you are right, we simply do not have all the information that we need to make a proper construction of the target probabilities.

I am still wrapping my head around the modifications you made for estimating the symptom probabilities. I'll merge once I'm done
I'll make a PR after that to tidy the code up a bit as it starts to get really long, and also add an option to switch between the basic and advanced symptom parsers.
